name: trigger-cursor-on-label
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  trigger-on-issue:
    if: github.event_name == 'issues' && github.event.label.name == 'cursor-fix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "@cursor fix"
            })

  trigger-on-pr:
    if: github.event_name == 'pull_request' && github.event.label.name == 'cursor-fix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "@cursor fix"
            })
